const test = require('node:test');
const assert = require('node:assert/strict');
const C = require('../web/research-core.js');
const base = () => ({nodes:[{id:'r',title:'Root',node_type:'root',body:'root'}, {id:'a',parent:'r',title:'A',body:'old'}],edges:[{source:'a',target:'r',type:'subtype_of'}]});
test('normalizes aliases without creating semantic edges', () => {const g=C.graph({nodes:base().nodes,edges:[{source_node_id:'a',target_node_id:'r',edge_type:'subtype_of'}]});assert.equal(g.edges.length,1);assert.equal(g.edges[0].source,'a');});
test('dangling references are disclosed', () => {const x=base();x.edges.push({source:'a',target:'missing'});const g=C.graph(x);assert.equal(g.edges.length,1);assert.equal(g.warnings.length,1);});
test('orphans stay orphaned', () => {const x=base();x.nodes.push({id:'orphan'});assert.equal(C.graph(x).edges.length,1);});
test('duplicate nodes fail', () => {const x=base();x.nodes.push({id:'a'});assert.throws(()=>C.graph(x));});
test('duplicate typed edges deduplicate', () => {const x=base();x.edges.push(x.edges[0]);assert.equal(C.graph(x).edges.length,1);});
test('different relation types remain distinct', () => {const x=base();x.edges.push({source:'a',target:'r',type:'exception_to'});assert.equal(C.graph(x).edges.length,2);});
test('synthetic relationship is not relabeled as observed', () => {const x=base();x.edges[0].synthetic=true;assert.equal(C.graph(x).edges[0].synthetic,true);});
test('body changes produce edits', () => {const a=C.graph(base()),b=C.graph(base());b.nodes[1].body='generalized';assert.equal(C.difference(a,b).changed.length,1);});
test('version labels alone do not claim a rule edit', () => {const a=C.graph(base()),b=C.graph(base());b.version='v2.1';assert.equal(C.difference(a,b).changed.length,0);});
test('retired node remains in the comparison evidence', () => {const a=C.graph(base()),b=C.graph(base());b.nodes.pop();assert.equal(C.difference(a,b).removed[0].id,'a');});
test('no parent means no implied comparison', () => {const g=C.graph(base());assert.equal(C.difference(null,g).added.length,2);});
test('parent traversal is cycle safe', () => {const a=[{id:'a',parent:'b'},{id:'b',parent:'a'}];assert.equal(C.ancestry('a',a).cycle,true);assert.equal(C.ancestry('a',a).path.length,2);});
test('layout is deterministic and bounded after relaxation', () => {const a=C.graph(base());const one=C.initialLayout(a.nodes),two=C.initialLayout(a.nodes);assert.deepEqual(one,two);C.relax(one,a.edges,two,70);for(const p of one.values()){assert.ok(Number.isFinite(p.x)&&p.x>=40&&p.x<=910);}});
test('hierarchical layout respects known ancestry', () => {const p=C.initialLayout(base().nodes,'hierarchy');assert.ok(p.get('a').x>p.get('r').x);});
test('zero FP gives positive upper Wilson bound', () => {const ci=C.wilson(0,300);assert.equal(ci[0],0);assert.ok(Math.abs(ci[1]-.0126429712)<1e-8);});
test('Wilson center case is symmetric', () => {const [lo,hi]=C.wilson(50,100);assert.ok(Math.abs(lo+hi-1)<1e-12);});
for(const [k,n] of [[-1,5],[6,5],[0,0],[1.5,10],[1,Infinity]])test(`invalid interval ${k}/${n} is not zero`,()=>assert.equal(C.wilson(k,n),null));
test('zero TP with errors is F1 zero, not omitted', () => {const r=C.fromCounts({n:2,n_abstained:0,confusion_matrix:{a:{b:1},b:{a:1}}},['a','b']);assert.equal(r.macro_f1,0);assert.equal(r.macro_fpr,1);assert.equal(r.coverage,1);});
test('absent classes remain undefined',()=>{const r=C.fromCounts({n:2,confusion_matrix:{a:{a:2}}},['a','b']);assert.equal(r.per_class[1].f1,null);assert.equal(r.macro_f1,1);assert.equal(r.coverage,null);});
test('all-abstention/empty counts are not perfect evidence',()=>assert.equal(C.fromCounts({n:0,n_abstained:8,confusion_matrix:{a:{a:0}}},['a']),null));
test('abstention coverage has explicit denominator',()=>{const r=C.fromCounts({n:2,n_abstained:2,confusion_matrix:{a:{a:1,b:1}}},['a','b']);assert.equal(r.coverage,.5);});
test('count mismatch invalidates recomputation',()=>assert.equal(C.fromCounts({n:10,confusion_matrix:{a:{a:1}}},['a']),null));
test('unknown truths are rejected instead of silently excluded',()=>assert.equal(C.fromCounts({confusion_matrix:{x:{a:1}}},['a']),null));
test('unknown predictions count as errors',()=>assert.equal(C.fromCounts({n:1,confusion_matrix:{a:{x:1}}},['a']).accuracy,0));
test('negative counts are not evidence',()=>assert.equal(C.fromCounts({confusion_matrix:{a:{a:-1}}},['a']),null));
test('missing values stay missing',()=>assert.equal(C.fromCounts({},['a']),null));
