/* Research notebook. Definitions, implemented controls, hypotheses, and evidence
 * limitations are intentionally separate. Renders without a running API. */
(() => {
  'use strict';
  const HTML = `<article class="rch-methods">
    <header class="rch-method-head"><span class="rch-eyebrow">RUSH / RESEARCH NOTEBOOK</span><h2>Policy learning is an empirical question.</h2><p>The research object is a versioned policy graph—not a larger prompt and not a prettier score. We study whether localized rules, expert feedback, and controlled evaluation improve decision quality across cases the optimizer did not get to inspect.</p></header>
    <nav class="rch-method-nav" aria-label="Methods notebook"><a href="#method-mechanism">Mechanism</a><a href="#method-measurement">Measurement</a><a href="#method-golden">Golden sets</a><a href="#method-gates">Gates & generalization</a><a href="#method-hypotheses">Research agenda</a><a href="#method-routing">Decision paths</a><a href="#method-knobs">Lab controls</a><a href="#method-plan">Ablation plan</a><a href="#method-literature">Related work</a></nav>
    <section id="method-mechanism"><span class="rch-eyebrow">01 / THE MECHANISM</span><h3>The policy graph is the parameter we edit.</h3><p>Let G<sub>k</sub> be the policy graph at step k. Its Markdown nodes contain decision criteria, boundaries, exceptions, and supporting context; its explicit edges describe relationships. The judge receives a rendered policy bundle or the configured structural digest. A node in the visualization is not automatically a separate model, an executable predicate, or a measured causal contributor.</p>
      <div class="rch-contract"><span><b>DATA</b>Golden labels & split identity</span><span><b>JUDGES</b>Predictions under G<sub>k</sub></span><span><b>ANCHORS</b>Misalignment evidence</span><span><b>DRAFTER</b>Bounded node edits</span><span><b>EVALUATION</b>Candidate vs incumbent</span><span><b>GATE</b>Accept / veto / retain</span></div>
      <div class="rch-equation">G<sub>k+1</sub> = G′<sub>k</sub> when the configured gate accepts; otherwise G<sub>k+1</sub> = G<sub>k</sub>.<small>This is a state transition, not a convergence theorem. A rejected proposal is part of the experimental record but does not become the deployed policy.</small></div>
      <div class="rch-method-grid"><div><h4>What runs today</h4><p>A seeded classification experiment, a configurable judge panel, error-driven anchor selection, localized policy proposals, deterministic scoring, configurable acceptance, and recorded human review. The GenAI and MNIST tasks use different label spaces but share the experimental machinery. Dataset labels are reference labels; they are not proof that an SME personally adjudicated every image.</p></div><div><h4>What the terminology does not imply</h4><p>The current loop optimizes policy text. It does not perform PPO or GRPO model-weight updates. Human feedback supplies labels, review, and future training data; storing a review does not demonstrate that a critic has been trained. A cap on edited files is a reviewability constraint, not a PPO probability-ratio clip.</p></div></div>
    </section>
    <section id="method-measurement"><span class="rch-eyebrow">02 / MEASUREMENT</span><h3>Keep the denominator visible.</h3><p>For each class, compute one-vs-rest true positives (TP), false positives (FP), false negatives (FN), and true negatives (TN). Report the per-class counts with aggregate scores. In MNIST, an aggregate FPR is a macro average over ten one-vs-rest problems—not the binary GenAI FPR and not production prevalence.</p>
      <div class="rch-method-grid"><div class="rch-equation">FPR = FP / (FP + TN)<br>FNR = FN / (FN + TP)<br>F1 = 2TP / (2TP + FP + FN)<small>When the F1 denominator is positive and TP = 0, F1 = 0. A genuinely undefined denominator remains undefined; it must not be silently replaced by evidence of success.</small></div><div class="rch-equation">Coverage = N<sub>decided</sub> / N<sub>evaluated</sub><br>Risk<sub>selective</sub> = N<sub>wrong, decided</sub> / N<sub>decided</sub><small>High quality after abstaining on difficult cases can coexist with low coverage. Compare the risk–coverage trade-off and review cost, not the conditional accuracy alone.</small></div></div>
      <p><strong>Legacy F1 correction.</strong> Older code could omit zero-F1 classes from the macro average. The branch corrects that computation; previously saved scores and acceptance decisions remain historical artifacts. Re-score saved predictions and establish a clean baseline before resuming a comparison. The workbench recomputes diagnostics when valid confusion counts are available and otherwise labels values as stored measurements. It does not rewrite a historic gate verdict.</p>
      <p><strong>Uncertainty belongs to the estimand.</strong> A Wilson interval can describe a single binomial rate under its sampling assumptions. It is not an interval for macro-F1, an automatic solution to correlated examples, or a repeated-testing correction. Paired comparisons should use the same held-out items and account for repeated seeds and relevant clusters; selecting the best arm changes the interpretation of its validation gain.</p>
      <div class="rch-calculator"><span class="rch-eyebrow">INTERACTIVE UNCERTAINTY CHECK / NOT AN EXPERIMENT RESULT</span><h4>Zero observed false positives does not mean zero risk.</h4><label>False positives<input id="methodFP" type="number" min="0" step="1" value="0"/></label><label>Evaluated negatives<input id="methodNegatives" type="number" min="1" step="1" value="300"/></label><output id="methodInterval" aria-live="polite"></output><p>Two-sided 95% Wilson interval for a single binomial rate. The inference assumes the evaluated negatives support that sampling model; distribution shift, clustering, and adaptive selection are not addressed by this calculation.</p></div>
    </section>
    <section id="method-golden"><span class="rch-eyebrow">03 / GOLDEN-SET DEVELOPMENT</span><h3>Label quality and coverage are separate axes.</h3><p>Agreement is not ground truth. Record who labeled an item, which policy version they used, whether they saw model suggestions, and what changed after adjudication. A multi-model panel may share systematic errors. A unanimous panel can disagree with the reference because the models are wrong, because the reference is wrong, or because the policy is ambiguous.</p>
      <div class="rch-table-scroll"><table><thead><tr><th>Signal</th><th>Operational use</th><th>What must be audited</th></tr></thead><tbody><tr><td>Reference disagreement + high model consensus</td><td>Prioritize investigation of a systematic error, mislabeled reference, or ambiguous policy.</td><td>Do not automatically relabel to the majority. Preserve original and revised labels with adjudicator provenance.</td></tr><tr><td>Reference disagreement + low consensus</td><td>Investigate hard boundaries and candidate rules.</td><td>A hard example need not be representative of production risk.</td></tr><tr><td>Reference agreement + low consensus</td><td>Study fragility, prompt sensitivity, and judge correlation.</td><td>Correct majority votes can hide unstable constituent judges.</td></tr><tr><td>Reference agreement + high consensus</td><td>Use a stratified audit sample as a control.</td><td>Auditing only disagreements misses shared, confidently wrong decisions.</td></tr></tbody></table></div>
      <p><strong>Label graduation is a workflow, not a theorem.</strong> Single-model, multi-model, non-expert human, multiple-human, SME, multiple-SME, and policy-expert judgments are possible provenance tiers. Select the reference tier for the application and measure reviewer disagreement. More votes or a higher title do not make a label infallible.</p>
      <p><strong>Coverage is not a node count.</strong> A policy can accumulate many rules while leaving important threat themes, languages, sources, or boundary conditions untested. Track golden-set support by policy node and slice, audit unanimous predictions, and add new examples through an explicit sampling design. Difficulty-driven training samples require a separate representative evaluation design for production claims.</p>
    </section>
    <section id="method-gates"><span class="rch-eyebrow">04 / ACCEPTANCE & GENERALIZATION</span><h3>A gate constrains an update. It does not prove a rule.</h3><div class="rch-equation">Accept in metric mode only when F1<sub>candidate, dev</sub> &gt; F1<sub>incumbent, dev</sub> + ε.<small>Metric + agent mode adds a veto; agent-only and gate-off are different experimental arms. The legacy field named “test” is development validation when the optimizer repeatedly consults it.</small></div>
      <p>The file-count limit, immutable policy versions, leakage checks, and metric gate make changes inspectable and can reduce failure risk. They do not prevent all overfitting. Repeatedly selecting on the same gate partition makes it adaptive validation. Reusing a cross-run benchmark to select prompts or configurations also turns that benchmark into development evidence.</p>
      <div class="rch-table-scroll"><table><thead><tr><th>Partition</th><th>Permitted role</th><th>Interpretation</th></tr></thead><tbody><tr><td>Training anchors</td><td>Expose examples and reference labels to the drafter.</td><td>Used to propose a generalization; not independent evidence that it works.</td></tr><tr><td>Gate partition</td><td>Choose among candidate edits.</td><td>Development validation even when stored under <code>test</code>.</td></tr><tr><td>Cross-run benchmark</td><td>Compare complete runs on the same manifest.</td><td>A development comparison if repeatedly consulted for selection.</td></tr><tr><td>Protected final evaluation</td><td>Evaluate the precommitted final selection without further tuning.</td><td>Evidence for a specified distribution; requires split provenance and an honest stopping rule.</td></tr><tr><td>Temporal / new-theme evaluation</td><td>Probe transfer to withheld themes or later production windows.</td><td>A separate generalization question, not implied by an in-distribution score.</td></tr></tbody></table></div>
      <p class="rch-method-note">The workbench's split audit checks available sample identifiers. Zero overlapping IDs does not detect near-duplicate images, source leakage, across-run reuse, or an exposed holdout. Missing IDs are reported as “not established,” not a pass.</p>
    </section>
    <section id="method-hypotheses"><span class="rch-eyebrow">05 / RESEARCH AGENDA</span><h3>Make each claim falsifiable.</h3><div class="rch-table-scroll"><table><thead><tr><th>Question</th><th>Controlled comparison</th><th>Failure criterion / measurement</th><th>Status</th></tr></thead><tbody>
      <tr><td>Do high-value anchors teach better rules?</td><td>Random misalignments vs confidence/error ranking vs importance ranking; match panel, splits, edit budget, and seeds.</td><td>No reproducible improvement in final FPR/FNR at matched coverage and labeling cost.</td><td>Selection controls implemented; result must be measured.</td></tr>
      <tr><td>Do bounded edits reduce harmful interference?</td><td>Vary the allowed node-edit budget. Keep untouched policy slices in the evaluation.</td><td>Target slice gains are offset by protected-slice regressions or uncontrolled prompt growth.</td><td>Budget control implemented; slice regression analysis remains a study protocol.</td></tr>
      <tr><td>How do bad golden labels deform the policy?</td><td>Seeded label-noise arms, clean paired controls, and blinded re-adjudication.</td><td>Compare graph drift, wrong-rule persistence, recovery, and reviewer reversals—not only end-point accuracy.</td><td>Noise controls implemented; expert-repair evaluation requires adjudication data.</td></tr>
      <tr><td>Does model diversity improve the measurement?</td><td>Single judges, matched-cost panels, and correlation-aware panel alternatives.</td><td>Additional judges repeat the same errors or increase cost without reducing risk.</td><td>Panel configuration implemented; correlation-aware weighting is a research alternative.</td></tr>
      <tr><td>Can routing reduce context without losing critical exceptions?</td><td>Full policy vs structural digest vs routed nodes vs hybrid deterministic execution.</td><td>Measure missed-rule retrieval, FPR/FNR, coverage, latency, and tokens under identical cases.</td><td>Full/digest controls exist; general graph routing and production hybrid execution are not implemented by this UI.</td></tr>
      <tr><td>Does the learned rule transfer to a new theme?</td><td>Leave-theme-out and temporal holdouts; fixed budgets and predeclared stopping.</td><td>A benefit disappears on new source families or future windows.</td><td>Proposed evaluation; not implied by MNIST or GenAI benchmark gains.</td></tr>
      </tbody></table></div>
    </section>
    <section id="method-routing"><span class="rch-eyebrow">06 / KNOWLEDGE GRAPH → DECISION PROGRAM</span><h3>Separate retrieval, observation, and execution.</h3><p>The d-ai-trader design motivates an important separation: deterministic selection of which guidelines are served, model-reported citations, and a decision outcome are different objects. An observed context → served rule → cited rule → action path is useful telemetry. It is not proof that the model executed that rule faithfully or that the cited rule caused the outcome.</p>
      <div class="rch-contract"><span><b>1 / RETRIEVAL</b>Choose relevant policy nodes</span><span><b>2 / OBSERVATION</b>Obtain typed, sourced facts</span><span><b>3 / EXECUTION</b>Evaluate explicit predicates</span><span><b>4 / ESCALATION</b>Unknown → expert review</span><span><b>5 / EVIDENCE</b>Measure against a reference</span></div>
      <p>The separate <a id="methodPaths" href="studio.html">shadow path sandbox</a> evaluates authored, version-pinned example programs with true/false/unknown branches. It does not infer those programs from arbitrary Markdown or execute them in the live classifiers. A deterministic function over a probabilistic image observation remains only as trustworthy as the observation, provenance, rule semantics, and coverage of its tests.</p><p><strong>Promotion protocol to investigate:</strong> author a typed predicate linked to a policy node, verify the policy pin and observation source, test positive / negative / boundary / missing-evidence cases, shadow it against the full-policy reference, then evaluate paired risk and coverage before any production integration. Audit both served-but-unused rules and cited-but-unserved rules; neither pattern alone proves a rule is dead weight.</p>
    </section>
    <section id="method-knobs"><span class="rch-eyebrow">07 / LAB CONTROLS</span><h3>The controls are the experimental design.</h3><p>The live form is authoritative for current selections. The table describes the role of each control, not a promise that a particular setting is optimal. Model availability and price depend on the configured provider.</p><div class="rch-table-scroll"><table><thead><tr><th>Control</th><th>What changes</th><th>What to keep comparable</th></tr></thead><tbody>
      <tr><td>Demo / label space</td><td>Binary GenAI or ten-class MNIST; policy area, manifests, and class semantics.</td><td>Do not pool the tasks' aggregate FPRs as though they share one binary denominator.</td></tr>
      <tr><td>Panel / compression</td><td>Selected judge models and each judge's full or structurally compressed policy.</td><td>Model version, decoding, input resolution, prompt render, and cache provenance.</td></tr>
      <tr><td>Seed / split seed</td><td>Experiment sampling versus source-manifest split assignment.</td><td>Same manifest identities and disjointness; the same seed alone cannot align different source trees.</td></tr>
      <tr><td>Cycles k / train N / gate T</td><td>Search budget, train mini-batch size, and development-validation size.</td><td>Evaluation budget and stopping rule. More attempts increase selection pressure.</td></tr>
      <tr><td>Drafter / input</td><td>The proposal model and text-only versus image-plus-text anchor context.</td><td>Drafter cost and information access; it must not receive protected final-evaluation answers.</td></tr>
      <tr><td>Anchor strategy / aligned anchors</td><td>Random misalignment, confidence/error prioritization, or importance ranking; optional correct controls.</td><td>Same anchor count and available pool. Confidence/error ranking is a heuristic, not a model-weight gradient.</td></tr>
      <tr><td>Max changes</td><td>The maximum policy-node files touched by one proposal.</td><td>Count cap is not a semantic edit-distance bound. Inspect each change.</td></tr>
      <tr><td>Gate mode / persona / ε</td><td>Metric-only; metric plus agent veto; agent-only; or off. ε adds a metric margin through API/CLI where supported.</td><td>These are distinct experimental arms. Persona does not supersede a metric wall in veto mode.</td></tr>
      <tr><td>Label cache / deweighting</td><td>Reuse compatible sampled predictions; exclude a flagged judge where configured.</td><td>Cache key, repeat count, judge inclusion, and coverage. Near-constant labels can also reflect class imbalance.</td></tr>
      <tr><td>Randomize gate / cycle</td><td>Resample the development comparison and re-evaluate the incumbent where supported.</td><td>Pair candidate and incumbent on identical items. Resampling does not eliminate adaptive selection bias.</td></tr>
      <tr><td>Label corruption / flip pool</td><td>Seeded experimental perturbation of development reference labels.</td><td>Clean evaluation, provenance of flipped IDs, and isolation from production/adjudication truth.</td></tr>
      <tr><td>Benchmark / holdout readouts</td><td>Additional start/final evaluation passes on configured manifests.</td><td>Additional cost, which cases were exposed, and whether results informed further selection.</td></tr>
      <tr><td>Concurrency</td><td>Parallel provider requests through API/CLI configuration.</td><td>Measure both latency and total cost; concurrency does not itself change the statistical sample size.</td></tr>
    </tbody></table></div></section>
    <section id="method-plan"><span class="rch-eyebrow">08 / REPRODUCIBILITY</span><h3>Write the comparison before selecting a winner.</h3><p>Export a draft ablation specification with the current lab inputs, seeds, primary endpoint, and fixed evaluation contract. This is a plan, not an execution queue: it cannot launch runs or authorize provider spending.</p><div class="rch-calculator"><label>Paired seeds<input id="methodSeeds" value="13,37,71" aria-label="Paired experiment seeds"/></label><label>Primary endpoint<select id="methodEndpoint"><option value="macro_fpr">Macro FPR</option><option value="macro_fnr">Macro FNR</option><option value="risk_at_matched_coverage">Risk at matched coverage</option></select></label><button type="button" id="methodExport">Export draft ablation plan</button><p id="methodPlanStatus" role="status"></p></div></section>
    <section id="method-literature"><span class="rch-eyebrow">09 / RELATED WORK & BOUNDARIES</span><h3>Borrow mechanisms. Test the transfer.</h3><p><a href="https://arxiv.org/abs/2507.19457" target="_blank" rel="noopener">GEPA</a> uses reflective prompt evolution and Pareto-based candidate selection. <a href="https://arxiv.org/abs/2601.04055" target="_blank" rel="noopener">Modular Prompt Optimization</a> studies section-local textual updates under a structured prompt schema. <a href="https://arxiv.org/abs/2608.10471" target="_blank" rel="noopener">RLMOpt</a> places adaptive search inside a deterministic scoring and selection harness. These are comparison mechanisms for matched experiments. This branch does not integrate those optimizers or claim to outperform their published results.</p><p>Use <a href="https://arxiv.org/abs/1707.06347" target="_blank" rel="noopener">PPO</a> and <a href="https://arxiv.org/abs/2402.03300" target="_blank" rel="noopener">DeepSeekMath / GRPO</a> for their actual weight-optimization definitions. The research aim is to isolate how policy locality, reference quality, and routing affect final decision risk. Feedback-driven policy iteration is a useful framing; claims about a particular optimizer must match its implemented objective and update rule.</p></section>
  </article>`;
  function init() {
    const host = document.getElementById('aboutContent'); if (!host || host.dataset.researchReady) return;
    host.dataset.researchReady = 'true'; host.innerHTML = HTML;
    const update = () => {
      const k = Number(document.getElementById('methodFP').value), n = Number(document.getElementById('methodNegatives').value);
      const interval = window.RushResearchCore?.wilson(k, n);
      document.getElementById('methodInterval').textContent = interval ? `Observed ${(k / n * 100).toFixed(2)}% · 95% interval [${(interval[0] * 100).toFixed(2)}%, ${(interval[1] * 100).toFixed(2)}%]` : 'Enter integer counts with 0 ≤ false positives ≤ negatives and negatives > 0.';
    };
    ['methodFP', 'methodNegatives'].forEach(id => document.getElementById(id).addEventListener('input', update)); update();
    document.getElementById('methodExport').addEventListener('click', () => {
      const tokens = document.getElementById('methodSeeds').value.split(',').map(x => x.trim());
      const seeds = tokens.map(Number), status = document.getElementById('methodPlanStatus');
      if (!tokens.length || tokens.length > 50 || tokens.some(x => !/^\d+$/.test(x)) || seeds.some(x => !Number.isSafeInteger(x)) || new Set(seeds).size !== seeds.length) {status.textContent = 'Use 1–50 distinct, nonnegative integer seeds.'; return;}
      const ids = ['experimentKMax','experimentBatchN','experimentTestN','experimentDrafterModel','experimentDrafterContext','experimentMaxChanges','experimentGateModel','experimentGatePersona','experimentStrategy','experimentMaxAnchors','experimentMaxAlignedAnchors'];
      const form = Object.fromEntries(ids.map(id => [id, document.getElementById(id)?.value ?? null]));
      const plan = {schema_version:1, kind:'draft_ablation_plan', execution_authorized:false, created_at:new Date().toISOString(),
        area:window.rushActiveDemo?.()?.policyGraph?.area ?? null, seeds, primary_endpoint:document.getElementById('methodEndpoint').value,
        arms:['random_misalignment','top_gradient','top_importance'], lab_inputs:form,
        judge_models:[...document.querySelectorAll('#runTriggerModels input.model-select-input:checked')].map(el => el.value),
        must_pin_before_execution:['source manifest hashes','base policy content hash','judge model/decoding versions','equal budget per arm','coverage constraint','protected final-evaluation protocol'],
        comparison:'Paired cases and seeds; precommit endpoint, stopping, and selection before final evaluation.'};
      const url = URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));
      const a = document.createElement('a'); a.href = url; a.download = 'rush-ablation-plan.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000);
      status.textContent = 'Draft exported. No run was started. Pin the missing manifest and policy identities before execution.';
    });
    const demo = window.rushActiveDemo?.()?.id || 'genai'; document.getElementById('methodPaths').href = `studio.html?demo=${encodeURIComponent(demo)}`;
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, {once:true}); else init();
})();
