/* Shared, source-linked methodology for the studio and the existing research lab. */
(() => {
  'use strict';
  window.rushMethodHTML = () => `
  <div class="method-doc about-doc">
    <div class="method-intro"><p class="eyebrow">METHOD &amp; EVIDENCE · REVIEWED 5 SEPTEMBER 2026</p><h1>A policy that learns.<br>A claim you can audit.</h1><p>RUSH turns golden-set evidence and expert adjudications into bounded edits to a versioned policy knowledge graph. The goal is to learn reusable decision criteria—not answers tied to individual examples.</p></div>
    <div class="method-callout"><p><strong>What is implemented:</strong> feedback-driven policy-text optimization, model-panel evaluation, configurable acceptance gates and versioned graph artifacts. The executive studio reads recorded snapshots. Its decision-path engine is an explicitly authored, version-pinned <strong>shadow demonstration</strong>, not production enforcement or an automatic natural-language compiler.</p></div>
    <section><h2>One learning loop. Three distinct artifacts.</h2><div class="method-grid"><div><h3>Evidence: the golden set</h3><p>Labels, adjudication history and representative coverage establish the reference. MNIST labels come from a dataset; they are not all fresh SME rulings. Agreement among models is not ground truth, and separate models need not have independent errors.</p><h3>Policy: the knowledge graph</h3><p>Versioned guidelines express intent, positive criteria, boundaries and exceptions. A new theme should motivate a general rule and a falsifying example. Accepted edits can add, change or retire nodes; node growth alone is not a quality metric.</p></div><div><h3>Execution: the decision program</h3><p>A knowledge graph is not automatically an executable DAG. A decision program needs typed predicates, explicit branch order, a policy-version pin and a complete unknown path. The shadow engine validates these contracts and routes unsupported evidence to expert review.</p><p>Deterministic traversal means the same program and supplied facts produce the same route. It does not make model-extracted visual facts accurate, nor does it prove an improvement in decision quality.</p></div></div></section>
    <section><h2>Call the optimizer what it is.</h2><p>The repository’s experimental loop drafts a small policy-file patch and scores it against golden labels. This is <strong>human-feedback-guided discrete policy/prompt optimization</strong>, with an RL-inspired propose–evaluate–accept loop. It does not, by itself, train model weights with PPO or GRPO. Recording human gate reviews creates feedback data; it is not evidence that a critic has already been trained.</p><table><thead><tr><th>Method</th><th>What changes</th><th>Relationship to RUSH</th></tr></thead><tbody>
      <tr><td><a href="https://arxiv.org/abs/1707.06347" target="_blank" rel="noopener noreferrer">PPO</a> / <a href="https://arxiv.org/abs/2402.03300" target="_blank" rel="noopener noreferrer">GRPO</a></td><td>A parameterized policy is updated using policy-gradient objectives.</td><td>A cap on edited files is not PPO’s clipped objective, and a metric gate is not a GRPO update. No such training is claimed here.</td></tr>
      <tr><td><a href="https://arxiv.org/abs/2507.19457" target="_blank" rel="noopener noreferrer">GEPA</a></td><td>Reflective prompt evolution, candidate evaluation and Pareto-based search.</td><td>A relevant comparator for textual optimization. RUSH is not presented as a GEPA implementation or as outperforming it.</td></tr>
      <tr><td><a href="https://arxiv.org/abs/2601.04055" target="_blank" rel="noopener noreferrer">Modular Prompt Optimization</a></td><td>Section-local textual edits in a structured prompt.</td><td>Relevant to bounded sub-policy edits. Localizing an edit helps inspectability; it does not guarantee transfer or prevent overfitting.</td></tr>
      <tr><td><a href="https://arxiv.org/abs/2608.10471" target="_blank" rel="noopener noreferrer">RLMOpt</a></td><td>Agent-directed prompt search with a deterministic evaluation harness.</td><td>An August 2026 research comparator for adaptive search and explicit constraints; not an integrated dependency or a proven RUSH result.</td></tr>
    </tbody></table><p><small>The supplied terms “GRPA” and “policy-opt” did not uniquely identify a verified method. This page uses the specific, sourced names above rather than silently asserting equivalence. Reported results in those papers belong to their experiments, not this demo.</small></p></section>
    <section><h2>Learn the rule—not the validation set.</h2><div class="method-equation">Train examples → propose a bounded patch<br>Development validation → compare incumbent and candidate<br>Protected final evaluation → estimate generalization</div><p>The repeatedly consulted “test” partition in the existing experiment API is <strong>development validation</strong>. Adaptive selection can overfit it even when every accepted step improves its score. Resampling helps but does not remove selection bias. A benchmark repeatedly inspected to choose configurations also becomes development evidence.</p><p>Bounded edits, hard negatives, leakage checks and expert review are risk controls—not proofs against overfitting. A release should be tested on representative, protected data, with sample counts, uncertainty, per-slice recall/FPR, abstention coverage and cost. A macro-F1 gain alone can hide regression on an important slice.</p><div class="method-callout"><p><strong>Scoring correction in this branch:</strong> F1 is computed from counts, <code>2TP / (2TP + FP + FN)</code>. A supported class with zero true positives has F1 = 0, not an undefined value to omit from the macro average. Entirely absent classes remain undefined under the documented convention. Historical gate scores are not silently rewritten and must be re-scored before comparison.</p></div><p>The existing gate has metric-only, metric-plus-agent-veto, agent-only and off modes. Only the first two enforce metric improvement. Agent-only and off are experimental controls, not production release safeguards.</p></section>
    <section><h2>Transfer the discipline—not the reward.</h2><p><a href="https://github.com/attdobi/d-ai-trader/blob/main/docs/POLICY_GRAPH.md" target="_blank" rel="noopener noreferrer">d-ai-trader’s policy graph</a> contributes useful patterns: versioned guideline identity, deterministic context-based prompt assembly, served-versus-cited logs and context → guideline → action → outcome views. Ordered rules written in a prompt are still interpreted by a model; they are not automatically executable code.</p><p>Market outcomes are delayed and confounded. A cited guideline’s P&amp;L is an association, not its causal contribution; co-cited rules cannot each claim additive credit for the same outcome. RUSH instead evaluates against adjudicated reference labels. In both systems, a model citation is a reported reference—not proof that the rule caused the decision.</p><div class="method-grid"><div><h3>Ready to inspect</h3><p>Read-only graph snapshots; per-run evolution when recorded lineage is available; content-level changes; typed shadow paths; explicit unknown handling; exportable program, facts and trace.</p></div><div><h3>Still requires validation</h3><p>Learned rule-to-code compilation, authenticated fact provenance, production path execution, calibrated visual extraction and measured judge-quality gains. The shadow demonstration does not modify labels, launch model calls or approve releases.</p></div></div></section>
    <section><h2>How to read the presentation</h2><p><strong>Recorded local history</strong> reads only existing policy and experiment artifacts. A snapshot collection is explicitly not a lineage. A run replay follows its recorded versions and retains the incumbent on rejected steps. Dry-run experiments are excluded from evidence. Missing files and incomplete history are disclosed.</p><p><strong>Illustrative walkthrough</strong> uses scripted policy examples and synthetic scenarios. It is always labeled; it carries no measured accuracy, performance, cost or gold-set coverage claims. The GenAI route does not classify an image as real merely because metadata or suspicious cues are absent.</p><p>Inspect the full experiment controls and existing adjudication workflow in the <a href="lab.html#loop">research lab</a>. Primary-source references above explain the research context; source code and test results define what this branch actually implements.</p></section>
  </div>`;
  const init = () => {
    const host = document.querySelector('#aboutContent');
    if (host) host.innerHTML = window.rushMethodHTML();
    // The legacy lab does not load studio.css. Scope the minimal reading styles.
    if (host && !document.querySelector('#studioView')) {
      // Keep legacy controls and ids intact while correcting presentation claims.
      const set = (selector, value) => { const el = document.querySelector(selector); if (el) el.textContent = value; };
      set('#heroH1', 'Controlled experiments. Evidence-led policy evolution.');
      set('#heroLede', 'Compare panel predictions with reference labels, draft bounded policy edits and audit the results. Quality improvement is an experimental question, not a guarantee.');
      set('#experiment .section-head p:not(.eyebrow)', 'Each seeded run proposes bounded policy edits from training evidence. The repeatedly consulted test partition is development validation, not an untouched test set. Metric-only and metric-plus-veto gates require improvement; agent-only and off modes do not. Recorded human reviews are feedback data, not proof of a trained critic.');
      const help = document.querySelectorAll('#experimentHelp .experiment-help-body > p');
      if (help[0]) help[0].textContent = 'Judges — the panel produces predictions; decision-quality metrics compare those predictions with reference labels. Near-constant output is a diagnostic flag, not proof that a judge ignored the policy. Deweighting changes the effective panel and must be considered when interpreting comparisons.';
      if (help[3]) help[3].textContent = 'Cost — depends on the configured train, validation and benchmark sizes, judge panel, cache behavior and resampling mode. Use the run ledger for measured spend rather than assuming a fixed benchmark size.';
      const input = document.querySelector('#experimentTestN');
      if (input?.parentElement?.firstChild?.nodeType === Node.TEXT_NODE) input.parentElement.firstChild.textContent = 'Validation size T';

      const style = document.createElement('style');
      style.textContent = '.method-doc{max-width:1050px;margin:auto;line-height:1.8}.method-doc h1{font-size:2.4rem;line-height:1.2}.method-doc section{margin:2.5rem 0;padding-top:1.5rem;border-top:1px solid #52606e}.method-grid{display:grid;grid-template-columns:1fr 1fr;gap:2rem}.method-doc td,.method-doc th{padding:1rem;text-align:left;vertical-align:top;line-height:1.7}.method-callout,.method-equation{padding:1rem 1.5rem;border-left:2px solid #b6bdc5;margin:1.5rem 0}.method-doc a{text-decoration:underline}.method-doc small{display:block;line-height:1.8}@media(max-width:700px){.method-grid{grid-template-columns:1fr}.method-doc table,.method-doc tbody,.method-doc tr,.method-doc td{display:block}.method-doc thead{display:none}.method-doc td{padding:.6rem 0}}';
      document.head.append(style);
    }
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, {once:true}); else init();
})();
