const nodes = [
  {id:'GA.root', title:'GenAI Image Classification', type:'root', polarity:'mixed', x:50, y:12, rule:'Root decision rule for gen_ai vs not_gen_ai.', edges:['GA.visual_artifacts.anatomy.hands','GA.visual_artifacts.text_symbols','GA.surface_texture.plastic_skin','GA.scene_geometry.inconsistent_perspective','GA.provenance.synthetic_disclosure','GA.boundary.photo_editing','GA.boundary.cgi_game_render','GA.boundary.low_quality_uncertain']},
  {id:'GA.visual_artifacts.anatomy.hands', title:'Hand / limb artifacts', type:'category', polarity:'positive', x:19, y:36, rule:'Extra, missing, fused, duplicated, or impossible hands/limbs.'},
  {id:'GA.visual_artifacts.text_symbols', title:'Garbled text', type:'category', polarity:'positive', x:40, y:36, rule:'Pseudo-text, malformed logos, impossible integrated typography.'},
  {id:'GA.surface_texture.plastic_skin', title:'Plastic skin', type:'category', polarity:'positive', x:61, y:36, rule:'Synthetic waxy/poreless texture not explained by filters.'},
  {id:'GA.scene_geometry.inconsistent_perspective', title:'Geometry', type:'category', polarity:'positive', x:82, y:36, rule:'Impossible reflections, shadows, object intersections, perspective.'},
  {id:'GA.provenance.synthetic_disclosure', title:'Provenance', type:'category', polarity:'positive', x:22, y:70, rule:'Watermark, metadata, caption, or source evidence identifies generation.'},
  {id:'GA.boundary.photo_editing', title:'Photo editing', type:'boundary', polarity:'hard-negative', x:45, y:74, rule:'Filters, retouching, compression, and healing-brush artifacts are not GenAI by themselves.'},
  {id:'GA.boundary.cgi_game_render', title:'CGI / game', type:'boundary', polarity:'hard-negative', x:65, y:74, rule:'Rendered or stylized assets are not GenAI unless generative provenance is established.'},
  {id:'GA.boundary.low_quality_uncertain', title:'Uncertain low quality', type:'boundary', polarity:'negative', x:85, y:74, rule:'Blurred/cropped/ambiguous cases require abstain or SME review.'}
];
const edges = [
  ['GA.root','GA.visual_artifacts.anatomy.hands'],['GA.root','GA.visual_artifacts.text_symbols'],['GA.root','GA.surface_texture.plastic_skin'],['GA.root','GA.scene_geometry.inconsistent_perspective'],['GA.root','GA.provenance.synthetic_disclosure'],['GA.root','GA.boundary.photo_editing'],['GA.root','GA.boundary.cgi_game_render'],['GA.root','GA.boundary.low_quality_uncertain'],['GA.surface_texture.plastic_skin','GA.boundary.photo_editing'],['GA.visual_artifacts.anatomy.hands','GA.boundary.photo_editing'],['GA.scene_geometry.inconsistent_perspective','GA.boundary.cgi_game_render'],['GA.visual_artifacts.text_symbols','GA.boundary.low_quality_uncertain']
];
const images = [
  {id:'ga_seed_0001', split:'development', tier:'gold', label:'gen_ai', nodes:['GA.visual_artifacts.anatomy.hands'], confidence:.86, note:'Placeholder impossible-hand positive.'},
  {id:'ga_seed_0002', split:'validation', tier:'gold', label:'not_gen_ai', nodes:['GA.boundary.photo_editing'], confidence:.72, note:'Placeholder conventional-edit hard negative.'},
  {id:'ga_seed_0003', split:'locked_holdout', tier:'provisional', label:'abstain', nodes:['GA.boundary.low_quality_uncertain'], confidence:.48, note:'Placeholder low-quality consensus-audit case.'}
];
const labels = [
  {image:'ga_seed_0001', labeler:'SME placeholder', label:'gen_ai', confidence:.86, evidence:'GA.visual_artifacts.anatomy.hands → extra/missing/fused digits', tier:'gold'},
  {image:'ga_seed_0002', labeler:'SME placeholder', label:'not_gen_ai', confidence:.72, evidence:'GA.boundary.photo_editing → edited does not equal generated', tier:'gold'},
  {image:'ga_seed_0003', labeler:'Future LLM ensemble', label:'abstain', confidence:.48, evidence:'GA.boundary.low_quality_uncertain → insufficient evidence', tier:'provisional'}
];
const suggestions = [
  {id:'patch.seed.001', type:'clarification_with_examples', status:'pending SME', title:'Separate plastic skin from beauty filters', rationale:'Expected high-density boundary likely to drive false positives.', diff:'+ boundary example under GA.boundary.photo_editing\n+ note: beauty filter causing poreless skin => not_gen_ai unless stronger evidence'},
  {id:'patch.seed.002', type:'new_subcategory', status:'pending SME', title:'Prepare repeated-detail artifact node', rationale:'If early labels cite generated jewelry, teeth, or repeated objects repeatedly, add a dedicated subtype.', diff:'+ node GA.visual_artifacts.repeated_details\n+ edge subtype_of GA.root'}
];
const metrics = {accuracy:1, precision:1, recall:1, fpr:0, positive_proportion:.5, informedness:1, coverage:.08, gray_zone_mass:.34};

document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(btn.dataset.tab).classList.add('active')}));
function byId(id){return nodes.find(n=>n.id===id)}
function drawGraph(){const c=document.getElementById('graphCanvas');const rect=()=>c.getBoundingClientRect();edges.forEach(([a,b])=>{const na=byId(a), nb=byId(b);const line=document.createElement('div');line.className='graph-line';const update=()=>{const w=c.clientWidth,h=c.clientHeight;const x1=na.x*w/100,y1=na.y*h/100,x2=nb.x*w/100,y2=nb.y*h/100;const len=Math.hypot(x2-x1,y2-y1);line.style.width=len+'px';line.style.left=x1+'px';line.style.top=y1+'px';line.style.transform=`rotate(${Math.atan2(y2-y1,x2-x1)}rad)`};c.appendChild(line);update();window.addEventListener('resize',update)});nodes.forEach(n=>{const el=document.createElement('button');el.className=`graph-node ${n.type==='boundary'?'boundary':n.polarity}`;el.style.left=n.x+'%';el.style.top=n.y+'%';el.innerHTML=`${n.title}<br><span style="color:#aab8d3;font-weight:650">${n.id}</span>`;el.addEventListener('click',()=>showNode(n));c.appendChild(el)});showNode(nodes[0])}
function showNode(n){document.getElementById('nodeDetails').innerHTML=`<h3>${n.title}</h3><p><strong>${n.id}</strong> · ${n.type} · ${n.polarity}</p><p>${n.rule}</p><ul><li>Version: Generative_AI.v0.1</li><li>Stores source anchors, coverage targets, examples, and boundary/confusion edges in Markdown frontmatter.</li><li>Future labelers cite this node when producing justification and confidence.</li></ul>`}
function renderGolden(){document.getElementById('goldenGrid').innerHTML=images.map(i=>`<article class="golden-card"><div class="thumb">image pending</div><span class="badge ${i.tier==='gold'?'gold':'provisional'}">${i.tier}</span><h3>${i.id}</h3><p>${i.note}</p><p><strong>${i.label}</strong> · ${Math.round(i.confidence*100)}% · ${i.split}</p><p>${i.nodes.join('<br>')}</p></article>`).join('')}
function renderLabels(){document.getElementById('labelTable').innerHTML=`<table><thead><tr><th>Image</th><th>Labeler</th><th>Label</th><th>Conf.</th><th>Policy evidence</th><th>Tier</th></tr></thead><tbody>${labels.map(l=>`<tr><td>${l.image}</td><td>${l.labeler}</td><td>${l.label}</td><td>${Math.round(l.confidence*100)}%</td><td>${l.evidence}</td><td><span class="badge ${l.tier==='gold'?'gold':'provisional'}">${l.tier}</span></td></tr>`).join('')}</tbody></table>`}
function renderDiffs(){document.getElementById('diffList').innerHTML=suggestions.map(s=>`<article class="diff-card"><p class="eyebrow">${s.type} · ${s.status}</p><h3>${s.title}</h3><p>${s.rationale}</p><pre>${s.diff}</pre></article>`).join('')}
function renderMetrics(){const format=(k,v)=>k==='fpr'||k.includes('proportion')||k.includes('coverage')||k.includes('mass')?`${Math.round(v*100)}%`:v.toFixed(2);document.getElementById('metricCards').innerHTML=Object.entries(metrics).map(([k,v])=>`<article class="metric-card"><div class="metric-label">${k.replaceAll('_',' ')}</div><div class="metric-value">${format(k,v)}</div></article>`).join('')}
drawGraph();renderGolden();renderLabels();renderDiffs();renderMetrics();
