(() => {
  const DEFAULT_GROW_MODEL = 'openai/gpt-5.5';

  const MNIST_PROMPT = `You are RUSH's policy-graph MNIST digit labeler.

Classify the supplied image as one of the ten digit classes defined in
MNIST_Digits.v0.1, using ONLY the policy document and graph context
pack below. Do not import outside priors about MNIST, do not rely on
filenames, indices, or metadata. If the policy is silent on something
you observe, say so and abstain.

[IMAGE]
{{image}}

[POLICY DOCUMENT]
{{policy_document_markdown}}   # MD.root.md + MD.digit.0..9.md

[GRAPH CONTEXT PACK]
Nodes:
{{node_context}}               # id, title, positive criteria, distinguishing features
Confused-with edges:
{{confused_with_edges}}        # e.g. 8 ↔ 3, 8 ↔ 0, per MD.digit.8.md
Canonical examples:
{{canonical_examples}}         # empty in v0.1

Workflow (hidden reasoning; only the final JSON is returned):
1. Inspect the glyph. Note observable features: loops (enclosed
   regions), strokes, crossbars, tails, top/bottom bowls, symmetry.
2. For each MD.digit.N node, check whether the Positive criteria are
   satisfied.
3. If more than one node's positive criteria are satisfied, walk each
   confused_with edge and apply the Distinguishing feature that
   separates the pair (e.g. "8 vs 3: closed left side → 8; open left
   side → 3").
4. Commit to the digit whose criteria are most fully satisfied. If two
   or more remain tied, abstain.
5. Set difficulty by how many distinguishing steps you needed; set
   is_boundary=true if you traversed any confused_with edge; set
   confidence honestly.

Return EXACTLY this JSON shape and no extra text:
{
  "label": "0|1|2|3|4|5|6|7|8|9|abstain",
  "justification": "<policy-grounded rationale naming MD.digit.N and, if used, the confused_with sibling>",
  "difficulty": "low|medium|high",
  "confidence": <number in [0,1]>,
  "is_boundary": <true|false>
}`;

  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    "'": '&#39;',
    '"': '&quot;'
  }[char]));

  function activeDemo() {
    return typeof window.rushActiveDemo === 'function'
      ? window.rushActiveDemo()
      : { id: 'genai', title: 'GenAI Image Classification' };
  }

  function renderMnist() {
    return `
      <article class="provenance-card">
        <div class="provenance-card-head">
          <div>
            <p class="provenance-kicker">Gp-0 Provenance</p>
            <h3>MNIST_Digits.v0.1</h3>
          </div>
          <span class="provenance-status">Defined · not yet executed · no labels collected</span>
        </div>
        <div class="provenance-grid">
          <section class="provenance-subsection">
            <h4>Cold-start seed</h4>
            <p>The MNIST_Digits v0.1 policy graph is a cold-start seed authored by an engineer agent running on Claude Opus 4-8 (commit 6b985a35), from digit stroke/topology domain knowledge plus the known confusion pairs 4/9, 3/5, 7/1, 8/3. It was not generated by running a model over images.</p>
          </section>
          <section class="provenance-subsection">
            <h4>Drafting model</h4>
            <p><strong>Drafting/seed model:</strong> Claude Opus 4-8 (cold-start seed, commit 6b985a35)</p>
          </section>
        </div>
        <section class="provenance-subsection provenance-prompt-block">
          <div class="provenance-subsection-head">
            <h4>Gp-0 — Generator/labeler prompt (defined; not yet executed; no labels collected)</h4>
            <a href="../docs/mnist-prompt-v0.md">Prompt spec</a>
          </div>
          <p>The prompt contract is defined for the MNIST track, but it has not been executed here and no Gp-0 labels have been collected.</p>
          <pre><code>${esc(MNIST_PROMPT)}</code></pre>
        </section>
      </article>`;
  }

  function renderGenai() {
    return `
      <article class="provenance-card">
        <div class="provenance-card-head">
          <div>
            <p class="provenance-kicker">Gp-0 Provenance</p>
            <h3>Generative_AI policy graph</h3>
          </div>
          <span class="provenance-status provenance-status--quiet">Track provenance</span>
        </div>
        <div class="provenance-grid">
          <section class="provenance-subsection">
            <h4>Policy track</h4>
            <p>This is the GenAI image-classification track. Its policy graph is the Generative_AI graph used by the original RUSH demo, with the active demo version selected from the policy graph controls.</p>
          </section>
          <section class="provenance-subsection">
            <h4>Drafting model</h4>
            <p><strong>Drafting/seed model:</strong> ${esc(DEFAULT_GROW_MODEL)}</p>
          </section>
        </div>
        <section class="provenance-subsection provenance-reference-block">
          <h4>Generator/labeler prompt reference</h4>
          <p>The GenAI labeler prompt contract is documented separately. It defines the binary image-labeling output shape and policy-grounded justification expectations; this panel does not claim a fresh Gp-0 execution.</p>
          <a href="../docs/llm-prompt-template.md">docs/llm-prompt-template.md</a>
        </section>
      </article>`;
  }

  function renderProvenance() {
    const panel = document.getElementById('provenancePanel');
    if (!panel) return;
    const demo = activeDemo();
    panel.innerHTML = demo?.id === 'mnist' ? renderMnist() : renderGenai();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderProvenance, { once: true });
  } else {
    renderProvenance();
  }

  document.getElementById('demoSelector')?.addEventListener('change', renderProvenance);
})();
